schema_version: 1

context:
  name: myokit
  version: 1.37.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/myokit-${{ version }}.tar.gz
  sha256: 90384f232bd1d7ed85a959158d6953fa3365c38746e18a072a73cb19e619145d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - myokit = myokit.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - configparser
    - lxml
    - matplotlib-base >=2.2
    - numpy
    - setuptools

tests:
  - python:
      imports:
        - myokit
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - myokit --help

about:
  summary: A modeling and simulation tool for cardiac cellular electrophysiology
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - myokit/tests/data/formats/sbml/LICENSE
    - myokit/tests/data/formats/cellml/LICENSE
    - myokit/_bin/sundials-win-vs/LICENSE
  homepage: http://myokit.org

extra:
  recipe-maintainers:
    - synapticarbors
    - MichaelClerx
